time --> passive: cold blood (alicia)
passive --> frost_enemy: cold blood (alicia)
passive --> damage_dealt: cold blood (alicia)
ultimate_cast --> frost_enemy: ice shock (alicia)
ultimate_cast --> ultimate_hit: ice shock (alicia)
ultimate_hit --> damage_dealt: ice shock (alicia)
normal_attack_hit --> passive: ice soul sword (alicia,trait)
magic_damage_taken --> frost_enemy: fitzgerald (alicia,trait)
