ultimate_cast --> ultimate_hit: equalize (alloya)
ultimate_hit --> damage_dealt: equalize (alloya)
ultimate_cast --> mech_destroyed_self: drone detonation (alloya,trait)
mech_destroyed_self --> heal_self: part reuse (alloya,trait)
time --> mana: endless fuel belt (alloya,trait)
