magic_damage_taken --> passive: pain absorption (asuka)
passive --> mana: pain absorption (asuka)
ultimate_cast --> ultimate_hit: foxfire (asuka)
ultimate_hit --> damage_dealt: foxfire (asuka)
ultimate_hit --> heal_self: ninth tail (asuka,trait)
ultimate_hit --> vulnerable_enemy: night hunt (asuka,trait)
ultimate_hit --> frost_enemy: night hunt (asuka,trait)
ultimate_hit --> toxin_enemy: night hunt (asuka,trait)
time --> vulnerable_enemy: taizoukai (asuka,trait)
time --> frost_enemy: taizoukai (asuka,trait)
time --> toxin_enemy: taizoukai (asuka,trait)
passive --> heal_self: kongoukai (asuka,trait)
