normal_attack_taken --> passive: holy bastion (brynhild)
passive --> shield_self: holy bastion (brynhild)
ultimate_cast --> ultimate_hit: penitent smite (brynhild)
ultimate_hit --> damage_dealt: penitent smite (brynhild)
normal_attack_taken --> damage_dealt: counterstrike (brynhild,trait)
