combat_start --> damage_dealt: sky splitter slash (crit)
crit --> damage_dealt: light of chance (crit,evasion)
crit --> heal_self: life tide (crit,heal)
crit --> shield_self: unbreakable (crit,shield)
crit --> innerfire_self: blood rage (crit,innerfire)
crit --> vulnerable_enemy: fatal strike (crit,vulnerable)
crit --> frost_enemy: crystal shard (crit,frost)
crit --> toxin_enemy: bad infection (crit,toxin)
