time --> passive: life drain (cull)
passive --> damage_dealt: life drain (cull)
passive --> mana: life drain (cull)
passive --> heal_self: life drain (cull)
ultimate_cast --> ultimate_hit: death grip (cull)
ultimate_hit --> damage_dealt: death grip (cull)
ultimate_hit --> vulnerable_enemy: death grip (cull)
passive --> vulnerable_enemy: countdown (cull,trait)
normal_attack_hit --> passive: candlelight (cull,trait)
