time --> dodge_hit: enemy attacks
dodge_hit --> damage_dealt: phantom dance (evasion)
dodge_hit --> damage_dealt: wheel of fate (evasion)
dodge_hit --> damage_dealt: light of chance (evasion,crit)
dodge_hit --> heal_self: eternal rebirth (evasion,heal)
dodge_hit --> innerfire_self: frenzied smoke (evasion,innerfire)
dodge_hit --> vulnerable_enemy: curse eye (evasion,vulnerable)
dodge_hit --> frost_enemy: frost trap (evasion,frost)
dodge_hit --> toxin_enemy: venom spray (evasion,toxin)
