combat_start --> frost_enemy: preemptive frost (frost)
physical_damage_taken --> frost_enemy: frost counter (frost)
magic_damage_taken --> frost_enemy: frost counter (frost)
toxin_damage_taken --> frost_enemy: frost counter (frost)
true_damage_taken --> frost_enemy: frost counter (frost)
time --> frost_enemy: frozen touch (frost)
time --> damage_dealt: avalanche (frost)
time --> damage_dealt: frostfire storm (frost,innerfire)
frost_enemy --> damage_dealt: crystal blade (frost)
