lethal_damage_taken --> heal_self: adrenaline (heal)
damage_dealt --> heal_self: revival breath (heal)
time --> heal_self: healing touch (heal)
time --> damage_dealt: life flower (heal)
heal_self --> damage_dealt: healing lightspear (heal)
heal_self --> innerfire_self: desperate plea (heal,innerfire)
heal_self --> vulnerable_enemy: bloody curse (heal,vulnerable)
heal_self --> frost_enemy: crystal blood (heal,frost)
heal_self --> toxin_enemy: plague source (heal,toxin)
