time --> damage_dealt: rebirth flame (health)
time --> heal_self: self-healing body (health,heal)
time --> shield_self: undying body (health,shield)
time --> innerfire_self: undying phoenix (health,innerfire)
time --> vulnerable_enemy: crushing force (health,vulnerable)
time --> frost_enemy: frost giant (health,frost)
time --> toxin_enemy: corruption breath (health,toxin)
