ultimate_cast --> ultimate_hit: dread scream (hellsing)
ultimate_hit --> damage_dealt: dread scream (hellsing)
normal_attack_hit --> vulnerable_enemy: colin's apple (hellsing,trait)
time --> vulnerable_enemy: fragility (hellsing,trait)
