combat_start --> innerfire_self: boiling tar (innerfire)
physical_damage_taken --> innerfire_self: arrogant aura (innerfire)
magic_damage_taken --> innerfire_self: arrogant aura (innerfire)
toxin_damage_taken --> innerfire_self: arrogant aura (innerfire)
true_damage_taken --> innerfire_self: arrogant aura (innerfire)
time --> innerfire_self: flame surge (innerfire)
time --> damage_dealt: frostfire storm (innerfire,frost)
time --> damage_dealt: the judgement day (innerfire)
innerfire_self --> damage_dealt: soul offering (innerfire)
