magic_damage_taken --> passive: favor of light (jenny)
physical_damage_taken --> passive: favor of light (jenny)
toxin_damage_taken --> passive: favor of light (jenny)
true_damage_taken --> passive: favor of light (jenny)
passive --> heal_self: favor of light (jenny)
passive --> heal_self: favor of light (jenny)
passive --> heal_self: favor of light (jenny)
passive --> heal_self: favor of light (jenny)
ultimate_cast --> ultimate_hit: holy prayer (jenny)
ultimate_hit --> damage_dealt: holy prayer (jenny)
ultimate_cast --> heal_self: sunbathing (jenny,trait)
time --> heal_self: fast healing (jenny,trait)
ultimate_cast --> heal_self: lay on hands (jenny,trait)
normal_attack_hit --> passive: rain of light (jenny,trait)
