ultimate_cast --> shield_self: astral barricade (kay)
ultimate_cast --> ultimate_hit: astral barricade (kay)
ultimate_hit --> damage_dealt: astral barricade (kay)
time --> shield_self: mech protect (kay,trait)
magic_damage_taken --> shield_self: mech tenacious (kay,trait)
physical_damage_taken --> shield_self: mech tenacious (kay,trait)
toxin_damage_taken --> shield_self: mech tenacious (kay,trait)
true_damage_taken --> shield_self: mech tenacious (kay,trait)
combat_start --> shield_self: mech hardening (kay,trait)
