time --> damage_dealt: drone's laser (mech)
time --> damage_dealt: drone's attack (mech)
time --> heal_self: aerial resupply (mech,heal)
time --> shield_self: robust parts (mech,shield)
time --> innerfire_self: ion spark (mech,innerfire)
time --> vulnerable_enemy: system shutdown (mech,vulnerable)
time --> frost_enemy: magnetic cooling (mech,frost)
time --> toxin_enemy: virus code (mech,toxin)
mech_destroyed_self --> damage_dealt: self destruct (mech)
