frost_enemy --> passive: cryogenic circuit (mina)
passive --> mana: cryogenic circuit (mina)
ultimate_cast --> ultimate_hit: rapid cooling (mina)
ultimate_hit --> damage_dealt: rapid cooling (mina)
ultimate_hit --> frost_enemy: ski resort (mina,trait)
time --> frost_enemy: bubble serenade (mina,trait)
