time --> passive: poison gas (moriatee)
passive --> toxin_enemy: poison gas (moriatee)
damage_dealt --> damage_dealt: aggragegated outbreak (moriatee,trait)
physical_damage_taken --> toxin_enemy: res-pathogen (moriatee,trait)
normal_attack_hit --> passive: toxic hormone (moriatee,trait)
