combat_start --> shield_self: preemptive shield (shield)
lethal_damage_taken --> shield_self: solid miracle (shield)
time --> shield_self: shield surge (shield)
time --> damage_dealt: damage reflection (shield,vulnerable)
shield_self --> damage_dealt: flying shield (shield)
shield_self --> frost_enemy: ice barrier (shield,frost)
shield_self --> toxin_enemy: poison armor (shield,toxin)
