combat_start --> ultimate_cast: arcane storm (spell)
damage_dealt --> mana: magic mark (spell)
ultimate_cast --> mana: magic surge (spell)
ultimate_cast --> heal_self: heal spring (spell,heal)
ultimate_cast --> shield_self: mana shield (spell,shield)
ultimate_cast --> innerfire_self: holyfire tattoo (spell,innerfire)
ultimate_cast --> vulnerable_enemy: spell sharpness (spell,vulnerable)
ultimate_cast --> frost_enemy: frost magic ball (spell,frost)
ultimate_cast --> toxin_enemy: toxin magic ball (spell,toxin)
