combat_start --> passive: windwalker (sylvie)
passive --> dodge_hit: windwalker (sylvie)
ultimate_cast --> ultimate_hit: the hawk (sylvie)
ultimate_hit --> damage_dealt: the hawk (sylvie)
ultimate_cast --> passive: showtime (sylvie,trait)
normal_attack_hit --> passive: seize cover (sylvie,trait)
