combat_start --> toxin_enemy: preemptive poison (toxin)
time --> toxin_enemy: poison surge (toxin)
time --> damage_dealt: poison settles (toxin)
physical_damage_taken --> toxin_enemy: toxin backlash (toxin)
magic_damage_taken --> toxin_enemy: toxin backlash (toxin)
toxin_damage_taken --> toxin_enemy: toxin backlash (toxin)
true_damage_taken --> toxin_enemy: toxin backlash (toxin)
damage_dealt --> toxin_enemy: plague infection (toxin)
