combat_start --> vulnerable_enemy: preemptive pain (vulnerable)
time --> vulnerable_enemy: curse surge (vulnerable)
time --> vulnerable_enemy: curse formation (vulnerable)
time --> vulnerable_enemy: death erosion (vulnerable)
time --> damage_dealt: death erosion (vulnerable)
time --> damage_dealt: damage reflection (vulnerable,shield)
vulnerable_enemy --> frost_enemy: cold wound (vulnerable,frost)
vulnerable_enemy --> toxin_enemy: death touch (vulnerable,toxin)
