time --> damage_dealt: wind missile (weaponry)
normal_attack_hit --> heal_self: spear of healing (weaponry,heal)
normal_attack_hit --> shield_self: fierce counter (weaponry,shield)
normal_attack_hit --> innerfire_self: wild power (weaponry,innerfire)
normal_attack_hit --> vulnerable_enemy: devouring blade (weaponry,vulnerable)
normal_attack_hit --> frost_enemy: iceblade storm (weaponry,frost)
normal_attack_hit --> toxin_enemy: poison claw (weaponry,toxin)
