time --> passive: eye of fury (wukong)
passive --> innerfire_self: eye of fury (wukong)
ultimate_cast --> ultimate_hit: wishful staff (wukong)
ultimate_hit --> damage_dealt: wishful staff (wukong)
magic_damage_taken --> innerfire_self: petrificative (wukong,trait)
physical_damage_taken --> innerfire_self: indestructible (wukong,trait)
normal_attack_hit --> ultimate_cast: world cracker (wukong,trait)
